[2025-09-05T11:34:19.587+0545] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-09-05T11:34:19.594+0545] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: start_diabetes_stack.start_fastapi manual__2025-09-05T05:46:54.857621+00:00 [queued]>
[2025-09-05T11:34:19.598+0545] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: start_diabetes_stack.start_fastapi manual__2025-09-05T05:46:54.857621+00:00 [queued]>
[2025-09-05T11:34:19.598+0545] {taskinstance.py:2867} INFO - Starting attempt 2 of 2
[2025-09-05T11:34:19.611+0545] {taskinstance.py:2890} INFO - Executing <Task(BashOperator): start_fastapi> on 2025-09-05 05:46:54.857621+00:00
[2025-09-05T11:34:19.616+0545] {standard_task_runner.py:72} INFO - Started process 42740 to run task
[2025-09-05T11:34:19.619+0545] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'start_diabetes_stack', 'start_fastapi', 'manual__2025-09-05T05:46:54.857621+00:00', '--job-id', '368', '--raw', '--subdir', 'DAGS_FOLDER/bash_operator.py', '--cfg-path', '/tmp/tmpguili8tw']
[2025-09-05T11:34:19.620+0545] {standard_task_runner.py:105} INFO - Job 368: Subtask start_fastapi
[2025-09-05T11:34:19.649+0545] {task_command.py:467} INFO - Running <TaskInstance: start_diabetes_stack.start_fastapi manual__2025-09-05T05:46:54.857621+00:00 [running]> on host ashok-Nitro-ANV16-41
[2025-09-05T11:34:19.685+0545] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='ashok' AIRFLOW_CTX_DAG_ID='start_diabetes_stack' AIRFLOW_CTX_TASK_ID='start_fastapi' AIRFLOW_CTX_EXECUTION_DATE='2025-09-05T05:46:54.857621+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-09-05T05:46:54.857621+00:00'
[2025-09-05T11:34:19.686+0545] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-09-05T11:34:19.686+0545] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-09-05T11:34:19.686+0545] {logging_mixin.py:190} INFO - Current task name:start_fastapi state:running start_date:2025-09-05 05:49:19.594724+00:00
[2025-09-05T11:34:19.686+0545] {logging_mixin.py:190} INFO - Dag name:start_diabetes_stack and current dag run status:running
[2025-09-05T11:34:19.686+0545] {taskinstance.py:732} INFO - ::endgroup::
[2025-09-05T11:34:19.686+0545] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-09-05T11:34:19.687+0545] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'cd /home/ashok/mlops_project && nohup conda run -n mysecondenvironment uvicorn app:app --host 0.0.0.0 --port 8000 </dev/null >/tmp/fastapi.log 2>&1']
[2025-09-05T11:34:19.697+0545] {subprocess.py:99} INFO - Output:
[2025-09-05T11:35:21.930+0545] {subprocess.py:110} INFO - Command exited with return code 1
[2025-09-05T11:35:21.939+0545] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/ashok/miniconda3/envs/mysecondenvironment/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/ashok/miniconda3/envs/mysecondenvironment/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/ashok/miniconda3/envs/mysecondenvironment/lib/python3.8/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/ashok/miniconda3/envs/mysecondenvironment/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
  File "/home/ashok/miniconda3/envs/mysecondenvironment/lib/python3.8/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-09-05T11:35:21.942+0545] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-09-05T11:35:21.942+0545] {logging_mixin.py:190} INFO - Task start:2025-09-05 05:49:19.594724+00:00 end:2025-09-05 05:50:21.941595+00:00 duration:62.346871
[2025-09-05T11:35:21.942+0545] {logging_mixin.py:190} INFO - Task:<Task(BashOperator): start_fastapi> dag:<DAG: start_diabetes_stack> dagrun:<DagRun start_diabetes_stack @ 2025-09-05 05:46:54.857621+00:00: manual__2025-09-05T05:46:54.857621+00:00, state:running, queued_at: 2025-09-05 05:46:54.877972+00:00. externally triggered: True>
[2025-09-05T11:35:21.942+0545] {logging_mixin.py:190} INFO - Failure caused by Bash command failed. The command returned a non-zero exit code 1.
[2025-09-05T11:35:21.943+0545] {taskinstance.py:1226} INFO - Marking task as FAILED. dag_id=start_diabetes_stack, task_id=start_fastapi, run_id=manual__2025-09-05T05:46:54.857621+00:00, execution_date=20250905T054654, start_date=20250905T054919, end_date=20250905T055021
[2025-09-05T11:35:21.977+0545] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-09-05T11:35:21.978+0545] {standard_task_runner.py:124} ERROR - Failed to execute job 368 for task start_fastapi (Bash command failed. The command returned a non-zero exit code 1.; 42740)
Traceback (most recent call last):
  File "/home/ashok/miniconda3/envs/mysecondenvironment/lib/python3.8/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/home/ashok/miniconda3/envs/mysecondenvironment/lib/python3.8/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/home/ashok/miniconda3/envs/mysecondenvironment/lib/python3.8/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
  File "/home/ashok/miniconda3/envs/mysecondenvironment/lib/python3.8/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/home/ashok/miniconda3/envs/mysecondenvironment/lib/python3.8/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/home/ashok/miniconda3/envs/mysecondenvironment/lib/python3.8/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/home/ashok/miniconda3/envs/mysecondenvironment/lib/python3.8/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/ashok/miniconda3/envs/mysecondenvironment/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
  File "/home/ashok/miniconda3/envs/mysecondenvironment/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/ashok/miniconda3/envs/mysecondenvironment/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/ashok/miniconda3/envs/mysecondenvironment/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/home/ashok/miniconda3/envs/mysecondenvironment/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/ashok/miniconda3/envs/mysecondenvironment/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/ashok/miniconda3/envs/mysecondenvironment/lib/python3.8/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/ashok/miniconda3/envs/mysecondenvironment/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
  File "/home/ashok/miniconda3/envs/mysecondenvironment/lib/python3.8/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-09-05T11:35:22.004+0545] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-09-05T11:35:22.016+0545] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-09-05T11:35:22.017+0545] {local_task_job_runner.py:245} INFO - ::endgroup::
