[2025-09-04T13:04:16.333+0545] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-09-04T13:04:16.341+0545] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: diabetes_pipeline_setup.start_mlflow manual__2025-09-04T07:19:10.852677+00:00 [queued]>
[2025-09-04T13:04:16.344+0545] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: diabetes_pipeline_setup.start_mlflow manual__2025-09-04T07:19:10.852677+00:00 [queued]>
[2025-09-04T13:04:16.344+0545] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-09-04T13:04:16.356+0545] {taskinstance.py:2890} INFO - Executing <Task(BashOperator): start_mlflow> on 2025-09-04 07:19:10.852677+00:00
[2025-09-04T13:04:16.360+0545] {standard_task_runner.py:72} INFO - Started process 91191 to run task
[2025-09-04T13:04:16.364+0545] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'diabetes_pipeline_setup', 'start_mlflow', 'manual__2025-09-04T07:19:10.852677+00:00', '--job-id', '91', '--raw', '--subdir', 'DAGS_FOLDER/bash_operator.py', '--cfg-path', '/tmp/tmpgemhabp_']
[2025-09-04T13:04:16.364+0545] {standard_task_runner.py:105} INFO - Job 91: Subtask start_mlflow
[2025-09-04T13:04:16.389+0545] {task_command.py:467} INFO - Running <TaskInstance: diabetes_pipeline_setup.start_mlflow manual__2025-09-04T07:19:10.852677+00:00 [running]> on host ashok-Nitro-ANV16-41
[2025-09-04T13:04:16.430+0545] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='diabetes_pipeline_setup' AIRFLOW_CTX_TASK_ID='start_mlflow' AIRFLOW_CTX_EXECUTION_DATE='2025-09-04T07:19:10.852677+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-09-04T07:19:10.852677+00:00'
[2025-09-04T13:04:16.430+0545] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-09-04T13:04:16.430+0545] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-09-04T13:04:16.430+0545] {logging_mixin.py:190} INFO - Current task name:start_mlflow state:running start_date:2025-09-04 07:19:16.341197+00:00
[2025-09-04T13:04:16.430+0545] {logging_mixin.py:190} INFO - Dag name:diabetes_pipeline_setup and current dag run status:running
[2025-09-04T13:04:16.431+0545] {taskinstance.py:732} INFO - ::endgroup::
[2025-09-04T13:04:16.431+0545] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-09-04T13:04:16.431+0545] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'source ~/miniconda3/etc/profile.d/conda.sh && conda activate mysecondenvironment && mlflow server --backend-store-uri sqlite:///mlflow.db --default-artifact-root ./mlruns --host 0.0.0.0 --port 5000 -D']
[2025-09-04T13:04:16.440+0545] {subprocess.py:99} INFO - Output:
[2025-09-04T13:04:17.167+0545] {subprocess.py:106} INFO - Usage: mlflow server [OPTIONS]
[2025-09-04T13:04:17.168+0545] {subprocess.py:106} INFO - Try 'mlflow server --help' for help.
[2025-09-04T13:04:17.168+0545] {subprocess.py:106} INFO - 
[2025-09-04T13:04:17.168+0545] {subprocess.py:106} INFO - Error: No such option: -D
[2025-09-04T13:04:17.341+0545] {subprocess.py:110} INFO - Command exited with return code 2
[2025-09-04T13:04:17.346+0545] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/ashok/miniconda3/envs/mysecondenvironment/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/ashok/miniconda3/envs/mysecondenvironment/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/ashok/miniconda3/envs/mysecondenvironment/lib/python3.8/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/ashok/miniconda3/envs/mysecondenvironment/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
  File "/home/ashok/miniconda3/envs/mysecondenvironment/lib/python3.8/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2025-09-04T13:04:17.350+0545] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-09-04T13:04:17.350+0545] {logging_mixin.py:190} INFO - Task start:2025-09-04 07:19:16.341197+00:00 end:2025-09-04 07:19:17.350334+00:00 duration:1.009137
[2025-09-04T13:04:17.350+0545] {logging_mixin.py:190} INFO - Task:<Task(BashOperator): start_mlflow> dag:<DAG: diabetes_pipeline_setup> dagrun:<DagRun diabetes_pipeline_setup @ 2025-09-04 07:19:10.852677+00:00: manual__2025-09-04T07:19:10.852677+00:00, state:running, queued_at: 2025-09-04 07:19:10.878184+00:00. externally triggered: True>
[2025-09-04T13:04:17.350+0545] {logging_mixin.py:190} INFO - Failure caused by Bash command failed. The command returned a non-zero exit code 2.
[2025-09-04T13:04:17.350+0545] {taskinstance.py:1226} INFO - Marking task as UP_FOR_RETRY. dag_id=diabetes_pipeline_setup, task_id=start_mlflow, run_id=manual__2025-09-04T07:19:10.852677+00:00, execution_date=20250904T071910, start_date=20250904T071916, end_date=20250904T071917
[2025-09-04T13:04:17.372+0545] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-09-04T13:04:17.372+0545] {standard_task_runner.py:124} ERROR - Failed to execute job 91 for task start_mlflow (Bash command failed. The command returned a non-zero exit code 2.; 91191)
Traceback (most recent call last):
  File "/home/ashok/miniconda3/envs/mysecondenvironment/lib/python3.8/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/home/ashok/miniconda3/envs/mysecondenvironment/lib/python3.8/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/home/ashok/miniconda3/envs/mysecondenvironment/lib/python3.8/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
  File "/home/ashok/miniconda3/envs/mysecondenvironment/lib/python3.8/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/home/ashok/miniconda3/envs/mysecondenvironment/lib/python3.8/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/home/ashok/miniconda3/envs/mysecondenvironment/lib/python3.8/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/home/ashok/miniconda3/envs/mysecondenvironment/lib/python3.8/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/ashok/miniconda3/envs/mysecondenvironment/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
  File "/home/ashok/miniconda3/envs/mysecondenvironment/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/ashok/miniconda3/envs/mysecondenvironment/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/ashok/miniconda3/envs/mysecondenvironment/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/home/ashok/miniconda3/envs/mysecondenvironment/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/ashok/miniconda3/envs/mysecondenvironment/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/ashok/miniconda3/envs/mysecondenvironment/lib/python3.8/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/ashok/miniconda3/envs/mysecondenvironment/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
  File "/home/ashok/miniconda3/envs/mysecondenvironment/lib/python3.8/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2025-09-04T13:04:17.418+0545] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-09-04T13:04:17.430+0545] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-09-04T13:04:17.430+0545] {local_task_job_runner.py:245} INFO - ::endgroup::
