[2025-09-05T11:28:37.183+0545] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-09-05T11:28:37.191+0545] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: start_diabetes_stack.start_fastapi manual__2025-09-05T05:43:22.428634+00:00 [queued]>
[2025-09-05T11:28:37.195+0545] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: start_diabetes_stack.start_fastapi manual__2025-09-05T05:43:22.428634+00:00 [queued]>
[2025-09-05T11:28:37.195+0545] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-09-05T11:28:37.207+0545] {taskinstance.py:2890} INFO - Executing <Task(BashOperator): start_fastapi> on 2025-09-05 05:43:22.428634+00:00
[2025-09-05T11:28:37.213+0545] {standard_task_runner.py:72} INFO - Started process 39492 to run task
[2025-09-05T11:28:37.217+0545] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'start_diabetes_stack', 'start_fastapi', 'manual__2025-09-05T05:43:22.428634+00:00', '--job-id', '358', '--raw', '--subdir', 'DAGS_FOLDER/bash_operator.py', '--cfg-path', '/tmp/tmp4i3ce1hy']
[2025-09-05T11:28:37.217+0545] {standard_task_runner.py:105} INFO - Job 358: Subtask start_fastapi
[2025-09-05T11:28:37.244+0545] {task_command.py:467} INFO - Running <TaskInstance: start_diabetes_stack.start_fastapi manual__2025-09-05T05:43:22.428634+00:00 [running]> on host ashok-Nitro-ANV16-41
[2025-09-05T11:28:37.291+0545] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='ashok' AIRFLOW_CTX_DAG_ID='start_diabetes_stack' AIRFLOW_CTX_TASK_ID='start_fastapi' AIRFLOW_CTX_EXECUTION_DATE='2025-09-05T05:43:22.428634+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-09-05T05:43:22.428634+00:00'
[2025-09-05T11:28:37.292+0545] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-09-05T11:28:37.292+0545] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-09-05T11:28:37.292+0545] {logging_mixin.py:190} INFO - Current task name:start_fastapi state:running start_date:2025-09-05 05:43:37.191349+00:00
[2025-09-05T11:28:37.292+0545] {logging_mixin.py:190} INFO - Dag name:start_diabetes_stack and current dag run status:running
[2025-09-05T11:28:37.292+0545] {taskinstance.py:732} INFO - ::endgroup::
[2025-09-05T11:28:37.292+0545] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-09-05T11:28:37.293+0545] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'cd /home/ashok/mlops_project && nohup conda run -n mysecondenvironment uvicorn app:app --host 0.0.0.0 --port 8000 </dev/null >/tmp/fastapi.log 2>&1']
[2025-09-05T11:28:37.304+0545] {subprocess.py:99} INFO - Output:
[2025-09-05T11:29:39.739+0545] {subprocess.py:110} INFO - Command exited with return code 1
[2025-09-05T11:29:39.747+0545] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/ashok/miniconda3/envs/mysecondenvironment/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/ashok/miniconda3/envs/mysecondenvironment/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/ashok/miniconda3/envs/mysecondenvironment/lib/python3.8/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/ashok/miniconda3/envs/mysecondenvironment/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
  File "/home/ashok/miniconda3/envs/mysecondenvironment/lib/python3.8/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-09-05T11:29:39.752+0545] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-09-05T11:29:39.753+0545] {logging_mixin.py:190} INFO - Task start:2025-09-05 05:43:37.191349+00:00 end:2025-09-05 05:44:39.752397+00:00 duration:62.561048
[2025-09-05T11:29:39.753+0545] {logging_mixin.py:190} INFO - Task:<Task(BashOperator): start_fastapi> dag:<DAG: start_diabetes_stack> dagrun:<DagRun start_diabetes_stack @ 2025-09-05 05:43:22.428634+00:00: manual__2025-09-05T05:43:22.428634+00:00, state:running, queued_at: 2025-09-05 05:43:22.444512+00:00. externally triggered: True>
[2025-09-05T11:29:39.753+0545] {logging_mixin.py:190} INFO - Failure caused by Bash command failed. The command returned a non-zero exit code 1.
[2025-09-05T11:29:39.753+0545] {taskinstance.py:1226} INFO - Marking task as UP_FOR_RETRY. dag_id=start_diabetes_stack, task_id=start_fastapi, run_id=manual__2025-09-05T05:43:22.428634+00:00, execution_date=20250905T054322, start_date=20250905T054337, end_date=20250905T054439
[2025-09-05T11:29:39.782+0545] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-09-05T11:29:39.782+0545] {standard_task_runner.py:124} ERROR - Failed to execute job 358 for task start_fastapi (Bash command failed. The command returned a non-zero exit code 1.; 39492)
Traceback (most recent call last):
  File "/home/ashok/miniconda3/envs/mysecondenvironment/lib/python3.8/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/home/ashok/miniconda3/envs/mysecondenvironment/lib/python3.8/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/home/ashok/miniconda3/envs/mysecondenvironment/lib/python3.8/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
  File "/home/ashok/miniconda3/envs/mysecondenvironment/lib/python3.8/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/home/ashok/miniconda3/envs/mysecondenvironment/lib/python3.8/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/home/ashok/miniconda3/envs/mysecondenvironment/lib/python3.8/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/home/ashok/miniconda3/envs/mysecondenvironment/lib/python3.8/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/ashok/miniconda3/envs/mysecondenvironment/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
  File "/home/ashok/miniconda3/envs/mysecondenvironment/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/ashok/miniconda3/envs/mysecondenvironment/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/ashok/miniconda3/envs/mysecondenvironment/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/home/ashok/miniconda3/envs/mysecondenvironment/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/ashok/miniconda3/envs/mysecondenvironment/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/ashok/miniconda3/envs/mysecondenvironment/lib/python3.8/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/ashok/miniconda3/envs/mysecondenvironment/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
  File "/home/ashok/miniconda3/envs/mysecondenvironment/lib/python3.8/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-09-05T11:29:39.824+0545] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-09-05T11:29:39.836+0545] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-09-05T11:29:39.837+0545] {local_task_job_runner.py:245} INFO - ::endgroup::
