[2025-09-04T11:14:58.221+0545] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-09-04T11:14:58.230+0545] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: mlops_diabetes_pipeline.concept_drift manual__2025-09-04T05:28:49.473570+00:00 [queued]>
[2025-09-04T11:14:58.235+0545] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: mlops_diabetes_pipeline.concept_drift manual__2025-09-04T05:28:49.473570+00:00 [queued]>
[2025-09-04T11:14:58.235+0545] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-09-04T11:14:58.252+0545] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): concept_drift> on 2025-09-04 05:28:49.473570+00:00
[2025-09-04T11:14:58.268+0545] {standard_task_runner.py:72} INFO - Started process 68555 to run task
[2025-09-04T11:14:58.273+0545] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'mlops_diabetes_pipeline', 'concept_drift', 'manual__2025-09-04T05:28:49.473570+00:00', '--job-id', '68', '--raw', '--subdir', 'DAGS_FOLDER/mlops_diabetes_pipeline.py', '--cfg-path', '/tmp/tmp46026meo']
[2025-09-04T11:14:58.273+0545] {standard_task_runner.py:105} INFO - Job 68: Subtask concept_drift
[2025-09-04T11:14:58.312+0545] {task_command.py:467} INFO - Running <TaskInstance: mlops_diabetes_pipeline.concept_drift manual__2025-09-04T05:28:49.473570+00:00 [running]> on host ashok-Nitro-ANV16-41
[2025-09-04T11:14:58.371+0545] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='mlops_diabetes_pipeline' AIRFLOW_CTX_TASK_ID='concept_drift' AIRFLOW_CTX_EXECUTION_DATE='2025-09-04T05:28:49.473570+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-09-04T05:28:49.473570+00:00'
[2025-09-04T11:14:58.372+0545] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-09-04T11:14:58.373+0545] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-09-04T11:14:58.373+0545] {logging_mixin.py:190} INFO - Current task name:concept_drift state:running start_date:2025-09-04 05:29:58.230995+00:00
[2025-09-04T11:14:58.373+0545] {logging_mixin.py:190} INFO - Dag name:mlops_diabetes_pipeline and current dag run status:running
[2025-09-04T11:14:58.373+0545] {taskinstance.py:732} INFO - ::endgroup::
[2025-09-04T11:14:59.891+0545] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/ashok/miniconda3/envs/mysecondenvironment/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/ashok/miniconda3/envs/mysecondenvironment/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/ashok/miniconda3/envs/mysecondenvironment/lib/python3.8/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/ashok/miniconda3/envs/mysecondenvironment/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
  File "/home/ashok/miniconda3/envs/mysecondenvironment/lib/python3.8/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/ashok/miniconda3/envs/mysecondenvironment/lib/python3.8/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/ashok/miniconda3/envs/mysecondenvironment/lib/python3.8/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/ashok/mlops_project/monitoring/concept_drift_monitor.py", line 53, in monitor_concept_drift
    dashboard.calculate(reference_data=ref_data, current_data=cur_data, column_mapping=column_mapping)
  File "/home/ashok/miniconda3/envs/mysecondenvironment/lib/python3.8/site-packages/evidently/dashboard/dashboard.py", line 48, in calculate
    self.execute(reference_data, current_data, column_mapping)
  File "/home/ashok/miniconda3/envs/mysecondenvironment/lib/python3.8/site-packages/evidently/pipeline/pipeline.py", line 52, in execute
    self.analyzers_results[analyzer] = instance.calculate(
  File "/home/ashok/miniconda3/envs/mysecondenvironment/lib/python3.8/site-packages/evidently/analyzers/cat_target_drift_analyzer.py", line 112, in calculate
    result.target_metrics = get_one_column_drift(
  File "/home/ashok/miniconda3/envs/mysecondenvironment/lib/python3.8/site-packages/evidently/calculations/data_drift.py", line 87, in get_one_column_drift
    raise ValueError(f"Cannot find column '{column_name}' in current dataset")
ValueError: Cannot find column 'Diabetes_binary' in current dataset
[2025-09-04T11:14:59.896+0545] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-09-04T11:14:59.896+0545] {logging_mixin.py:190} INFO - Task start:2025-09-04 05:29:58.230995+00:00 end:2025-09-04 05:29:59.896456+00:00 duration:1.665461
[2025-09-04T11:14:59.897+0545] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): concept_drift> dag:<DAG: mlops_diabetes_pipeline> dagrun:<DagRun mlops_diabetes_pipeline @ 2025-09-04 05:28:49.473570+00:00: manual__2025-09-04T05:28:49.473570+00:00, state:running, queued_at: 2025-09-04 05:28:49.492206+00:00. externally triggered: True>
[2025-09-04T11:14:59.897+0545] {logging_mixin.py:190} INFO - Failure caused by Cannot find column 'Diabetes_binary' in current dataset
[2025-09-04T11:14:59.897+0545] {taskinstance.py:1226} INFO - Marking task as FAILED. dag_id=mlops_diabetes_pipeline, task_id=concept_drift, run_id=manual__2025-09-04T05:28:49.473570+00:00, execution_date=20250904T052849, start_date=20250904T052958, end_date=20250904T052959
[2025-09-04T11:14:59.921+0545] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-09-04T11:14:59.921+0545] {standard_task_runner.py:124} ERROR - Failed to execute job 68 for task concept_drift (Cannot find column 'Diabetes_binary' in current dataset; 68555)
Traceback (most recent call last):
  File "/home/ashok/miniconda3/envs/mysecondenvironment/lib/python3.8/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/home/ashok/miniconda3/envs/mysecondenvironment/lib/python3.8/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/home/ashok/miniconda3/envs/mysecondenvironment/lib/python3.8/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
  File "/home/ashok/miniconda3/envs/mysecondenvironment/lib/python3.8/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/home/ashok/miniconda3/envs/mysecondenvironment/lib/python3.8/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/home/ashok/miniconda3/envs/mysecondenvironment/lib/python3.8/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/home/ashok/miniconda3/envs/mysecondenvironment/lib/python3.8/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/ashok/miniconda3/envs/mysecondenvironment/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
  File "/home/ashok/miniconda3/envs/mysecondenvironment/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/ashok/miniconda3/envs/mysecondenvironment/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/ashok/miniconda3/envs/mysecondenvironment/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/home/ashok/miniconda3/envs/mysecondenvironment/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/ashok/miniconda3/envs/mysecondenvironment/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/ashok/miniconda3/envs/mysecondenvironment/lib/python3.8/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/ashok/miniconda3/envs/mysecondenvironment/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
  File "/home/ashok/miniconda3/envs/mysecondenvironment/lib/python3.8/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/ashok/miniconda3/envs/mysecondenvironment/lib/python3.8/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/ashok/miniconda3/envs/mysecondenvironment/lib/python3.8/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/ashok/mlops_project/monitoring/concept_drift_monitor.py", line 53, in monitor_concept_drift
    dashboard.calculate(reference_data=ref_data, current_data=cur_data, column_mapping=column_mapping)
  File "/home/ashok/miniconda3/envs/mysecondenvironment/lib/python3.8/site-packages/evidently/dashboard/dashboard.py", line 48, in calculate
    self.execute(reference_data, current_data, column_mapping)
  File "/home/ashok/miniconda3/envs/mysecondenvironment/lib/python3.8/site-packages/evidently/pipeline/pipeline.py", line 52, in execute
    self.analyzers_results[analyzer] = instance.calculate(
  File "/home/ashok/miniconda3/envs/mysecondenvironment/lib/python3.8/site-packages/evidently/analyzers/cat_target_drift_analyzer.py", line 112, in calculate
    result.target_metrics = get_one_column_drift(
  File "/home/ashok/miniconda3/envs/mysecondenvironment/lib/python3.8/site-packages/evidently/calculations/data_drift.py", line 87, in get_one_column_drift
    raise ValueError(f"Cannot find column '{column_name}' in current dataset")
ValueError: Cannot find column 'Diabetes_binary' in current dataset
[2025-09-04T11:14:59.969+0545] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-09-04T11:14:59.977+0545] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-09-04T11:14:59.978+0545] {local_task_job_runner.py:245} INFO - ::endgroup::
