[2025-09-05T10:41:23.231+0545] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-09-05T10:41:23.238+0545] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: start_diabetes_stack.start_mlflow manual__2025-09-05T04:56:11.052720+00:00 [queued]>
[2025-09-05T10:41:23.242+0545] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: start_diabetes_stack.start_mlflow manual__2025-09-05T04:56:11.052720+00:00 [queued]>
[2025-09-05T10:41:23.242+0545] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-09-05T10:41:23.256+0545] {taskinstance.py:2890} INFO - Executing <Task(BashOperator): start_mlflow> on 2025-09-05 04:56:11.052720+00:00
[2025-09-05T10:41:23.261+0545] {standard_task_runner.py:72} INFO - Started process 16760 to run task
[2025-09-05T10:41:23.264+0545] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'start_diabetes_stack', 'start_mlflow', 'manual__2025-09-05T04:56:11.052720+00:00', '--job-id', '327', '--raw', '--subdir', 'DAGS_FOLDER/bash_operator.py', '--cfg-path', '/tmp/tmpynhelx13']
[2025-09-05T10:41:23.265+0545] {standard_task_runner.py:105} INFO - Job 327: Subtask start_mlflow
[2025-09-05T10:41:23.292+0545] {task_command.py:467} INFO - Running <TaskInstance: start_diabetes_stack.start_mlflow manual__2025-09-05T04:56:11.052720+00:00 [running]> on host ashok-Nitro-ANV16-41
[2025-09-05T10:41:23.338+0545] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='ashok' AIRFLOW_CTX_DAG_ID='start_diabetes_stack' AIRFLOW_CTX_TASK_ID='start_mlflow' AIRFLOW_CTX_EXECUTION_DATE='2025-09-05T04:56:11.052720+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-09-05T04:56:11.052720+00:00'
[2025-09-05T10:41:23.339+0545] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-09-05T10:41:23.339+0545] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-09-05T10:41:23.339+0545] {logging_mixin.py:190} INFO - Current task name:start_mlflow state:running start_date:2025-09-05 04:56:23.238798+00:00
[2025-09-05T10:41:23.339+0545] {logging_mixin.py:190} INFO - Dag name:start_diabetes_stack and current dag run status:running
[2025-09-05T10:41:23.339+0545] {taskinstance.py:732} INFO - ::endgroup::
[2025-09-05T10:41:23.340+0545] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-09-05T10:41:23.340+0545] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'conda run -n mysecondenvironment mlflow ui --port 5000 >/tmp/mlflow.log 2>&1']
[2025-09-05T10:41:23.350+0545] {subprocess.py:99} INFO - Output:
[2025-09-05T10:53:08.232+0545] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-09-05T10:53:08.240+0545] {process_utils.py:132} INFO - Sending 15 to group 16760. PIDs of all processes in the group: [16765, 16766, 16768, 16781, 16807, 16809, 16810, 16811, 16812, 16760]
[2025-09-05T10:53:08.240+0545] {process_utils.py:87} INFO - Sending the signal 15 to group 16760
[2025-09-05T10:53:08.241+0545] {taskinstance.py:3094} ERROR - Received SIGTERM. Terminating subprocesses.
[2025-09-05T10:53:08.246+0545] {taskinstance.py:3095} ERROR - Stacktrace: 
  File "/home/ashok/miniconda3/envs/mysecondenvironment/bin/airflow", line 8, in <module>
    sys.exit(main())
  File "/home/ashok/miniconda3/envs/mysecondenvironment/lib/python3.8/site-packages/airflow/__main__.py", line 62, in main
    args.func(args)
  File "/home/ashok/miniconda3/envs/mysecondenvironment/lib/python3.8/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/home/ashok/miniconda3/envs/mysecondenvironment/lib/python3.8/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
  File "/home/ashok/miniconda3/envs/mysecondenvironment/lib/python3.8/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/home/ashok/miniconda3/envs/mysecondenvironment/lib/python3.8/site-packages/airflow/cli/commands/task_command.py", line 254, in _run_task_by_selected_method
    return _run_task_by_local_task_job(args, ti)
  File "/home/ashok/miniconda3/envs/mysecondenvironment/lib/python3.8/site-packages/airflow/cli/commands/task_command.py", line 322, in _run_task_by_local_task_job
    ret = run_job(job=job_runner.job, execute_callable=job_runner._execute)
  File "/home/ashok/miniconda3/envs/mysecondenvironment/lib/python3.8/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/ashok/miniconda3/envs/mysecondenvironment/lib/python3.8/site-packages/airflow/jobs/job.py", line 421, in run_job
    return execute_job(job, execute_callable=execute_callable)
  File "/home/ashok/miniconda3/envs/mysecondenvironment/lib/python3.8/site-packages/airflow/jobs/job.py", line 450, in execute_job
    ret = execute_callable()
  File "/home/ashok/miniconda3/envs/mysecondenvironment/lib/python3.8/site-packages/airflow/jobs/local_task_job_runner.py", line 171, in _execute
    self.task_runner.start()
  File "/home/ashok/miniconda3/envs/mysecondenvironment/lib/python3.8/site-packages/airflow/task/task_runner/standard_task_runner.py", line 55, in start
    self.process = self._start_by_fork()
  File "/home/ashok/miniconda3/envs/mysecondenvironment/lib/python3.8/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/home/ashok/miniconda3/envs/mysecondenvironment/lib/python3.8/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/home/ashok/miniconda3/envs/mysecondenvironment/lib/python3.8/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
  File "/home/ashok/miniconda3/envs/mysecondenvironment/lib/python3.8/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/home/ashok/miniconda3/envs/mysecondenvironment/lib/python3.8/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/home/ashok/miniconda3/envs/mysecondenvironment/lib/python3.8/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/home/ashok/miniconda3/envs/mysecondenvironment/lib/python3.8/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/ashok/miniconda3/envs/mysecondenvironment/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
  File "/home/ashok/miniconda3/envs/mysecondenvironment/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/ashok/miniconda3/envs/mysecondenvironment/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/ashok/miniconda3/envs/mysecondenvironment/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/home/ashok/miniconda3/envs/mysecondenvironment/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/ashok/miniconda3/envs/mysecondenvironment/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/ashok/miniconda3/envs/mysecondenvironment/lib/python3.8/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/ashok/miniconda3/envs/mysecondenvironment/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
  File "/home/ashok/miniconda3/envs/mysecondenvironment/lib/python3.8/site-packages/airflow/operators/bash.py", line 257, in execute
    result = self._run_inline_command(bash_path=bash_path, env=env)
  File "/home/ashok/miniconda3/envs/mysecondenvironment/lib/python3.8/site-packages/airflow/operators/bash.py", line 284, in _run_inline_command
    return self.subprocess_hook.run_command(
  File "/home/ashok/miniconda3/envs/mysecondenvironment/lib/python3.8/site-packages/airflow/hooks/subprocess.py", line 104, in run_command
    for raw_line in iter(self.sub_process.stdout.readline, b""):
  File "/home/ashok/miniconda3/envs/mysecondenvironment/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 3095, in signal_handler
    self.log.error("Stacktrace: \n%s", "".join(traceback.format_stack()))

[2025-09-05T10:53:08.246+0545] {subprocess.py:117} INFO - Sending SIGTERM signal to process group
[2025-09-05T10:53:08.253+0545] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/ashok/miniconda3/envs/mysecondenvironment/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/ashok/miniconda3/envs/mysecondenvironment/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/ashok/miniconda3/envs/mysecondenvironment/lib/python3.8/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/ashok/miniconda3/envs/mysecondenvironment/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
  File "/home/ashok/miniconda3/envs/mysecondenvironment/lib/python3.8/site-packages/airflow/operators/bash.py", line 257, in execute
    result = self._run_inline_command(bash_path=bash_path, env=env)
  File "/home/ashok/miniconda3/envs/mysecondenvironment/lib/python3.8/site-packages/airflow/operators/bash.py", line 284, in _run_inline_command
    return self.subprocess_hook.run_command(
  File "/home/ashok/miniconda3/envs/mysecondenvironment/lib/python3.8/site-packages/airflow/hooks/subprocess.py", line 104, in run_command
    for raw_line in iter(self.sub_process.stdout.readline, b""):
  File "/home/ashok/miniconda3/envs/mysecondenvironment/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 3097, in signal_handler
    raise AirflowTaskTerminated("Task received SIGTERM signal")
airflow.exceptions.AirflowTaskTerminated: Task received SIGTERM signal
[2025-09-05T10:53:08.258+0545] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-09-05T10:53:08.259+0545] {logging_mixin.py:190} INFO - Task start:2025-09-05 04:56:23.238798+00:00 end:2025-09-05 05:08:08.258180+00:00 duration:705.019382
[2025-09-05T10:53:08.259+0545] {logging_mixin.py:190} INFO - Task:<Task(BashOperator): start_mlflow> dag:<DAG: start_diabetes_stack> dagrun:<DagRun start_diabetes_stack @ 2025-09-05 04:56:11.052720+00:00: manual__2025-09-05T04:56:11.052720+00:00, state:running, queued_at: 2025-09-05 04:56:11.067685+00:00. externally triggered: True>
[2025-09-05T10:53:08.259+0545] {logging_mixin.py:190} INFO - Failure caused by Task received SIGTERM signal
[2025-09-05T10:53:08.259+0545] {taskinstance.py:1226} INFO - Marking task as UP_FOR_RETRY. dag_id=start_diabetes_stack, task_id=start_mlflow, run_id=manual__2025-09-05T04:56:11.052720+00:00, execution_date=20250905T045611, start_date=20250905T045623, end_date=20250905T050808
[2025-09-05T10:53:08.267+0545] {process_utils.py:80} INFO - Process psutil.Process(pid=16781, status='terminated', started='10:41:22') (16781) terminated with exit code None
[2025-09-05T10:53:08.292+0545] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-09-05T10:53:08.320+0545] {process_utils.py:80} INFO - Process psutil.Process(pid=16765, status='terminated', started='10:41:22') (16765) terminated with exit code None
[2025-09-05T10:53:08.321+0545] {process_utils.py:80} INFO - Process psutil.Process(pid=16760, status='terminated', exitcode=2, started='10:41:22') (16760) terminated with exit code 2
[2025-09-05T10:53:08.453+0545] {process_utils.py:80} INFO - Process psutil.Process(pid=16768, status='terminated', started='10:41:22') (16768) terminated with exit code None
[2025-09-05T10:53:08.480+0545] {process_utils.py:80} INFO - Process psutil.Process(pid=16811, status='terminated', started='10:41:23') (16811) terminated with exit code None
[2025-09-05T10:53:08.481+0545] {process_utils.py:80} INFO - Process psutil.Process(pid=16812, status='terminated', started='10:41:23') (16812) terminated with exit code None
[2025-09-05T10:53:08.573+0545] {process_utils.py:80} INFO - Process psutil.Process(pid=16807, status='terminated', started='10:41:23') (16807) terminated with exit code None
[2025-09-05T10:53:08.573+0545] {process_utils.py:80} INFO - Process psutil.Process(pid=16766, status='terminated', started='10:41:22') (16766) terminated with exit code None
[2025-09-05T10:53:08.574+0545] {process_utils.py:80} INFO - Process psutil.Process(pid=16810, status='terminated', started='10:41:23') (16810) terminated with exit code None
[2025-09-05T10:53:08.574+0545] {process_utils.py:80} INFO - Process psutil.Process(pid=16809, status='terminated', started='10:41:23') (16809) terminated with exit code None
[2025-09-05T10:53:10.655+0545] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-09-05T10:53:10.663+0545] {taskinstance.py:2604} INFO - Dependencies not met for <TaskInstance: start_diabetes_stack.start_mlflow manual__2025-09-05T04:56:11.052720+00:00 [up_for_retry]>, dependency 'Not In Retry Period' FAILED: Task is not ready for retry yet but will be retried automatically. Current date is 2025-09-05T05:08:10.663461+00:00 and task will be retried at 2025-09-05T05:09:08.258180+00:00.
[2025-09-05T10:53:10.663+0545] {local_task_job_runner.py:166} INFO - Task is not able to be run
