[2025-09-21T09:46:46.282+0545] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-09-21T09:46:46.290+0545] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: mlops_diabetes_pipeline.generate_shap_explanations manual__2025-09-21T04:00:40.530929+00:00 [queued]>
[2025-09-21T09:46:46.293+0545] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: mlops_diabetes_pipeline.generate_shap_explanations manual__2025-09-21T04:00:40.530929+00:00 [queued]>
[2025-09-21T09:46:46.293+0545] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-09-21T09:46:46.306+0545] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): generate_shap_explanations> on 2025-09-21 04:00:40.530929+00:00
[2025-09-21T09:46:46.317+0545] {standard_task_runner.py:72} INFO - Started process 52011 to run task
[2025-09-21T09:46:46.320+0545] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'mlops_diabetes_pipeline', 'generate_shap_explanations', 'manual__2025-09-21T04:00:40.530929+00:00', '--job-id', '725', '--raw', '--subdir', 'DAGS_FOLDER/mlops_diabetes_pipeline.py', '--cfg-path', '/tmp/tmpy0chlm0w']
[2025-09-21T09:46:46.320+0545] {standard_task_runner.py:105} INFO - Job 725: Subtask generate_shap_explanations
[2025-09-21T09:46:46.343+0545] {task_command.py:467} INFO - Running <TaskInstance: mlops_diabetes_pipeline.generate_shap_explanations manual__2025-09-21T04:00:40.530929+00:00 [running]> on host ashok-Nitro-ANV16-41
[2025-09-21T09:46:46.385+0545] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='koiralaashok02@gmail.com' AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='mlops_diabetes_pipeline' AIRFLOW_CTX_TASK_ID='generate_shap_explanations' AIRFLOW_CTX_EXECUTION_DATE='2025-09-21T04:00:40.530929+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-09-21T04:00:40.530929+00:00'
[2025-09-21T09:46:46.386+0545] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-09-21T09:46:46.386+0545] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-09-21T09:46:46.386+0545] {logging_mixin.py:190} INFO - Current task name:generate_shap_explanations state:running start_date:2025-09-21 04:01:46.290301+00:00
[2025-09-21T09:46:46.387+0545] {logging_mixin.py:190} INFO - Dag name:mlops_diabetes_pipeline and current dag run status:running
[2025-09-21T09:46:46.387+0545] {taskinstance.py:732} INFO - ::endgroup::
[2025-09-21T09:46:47.147+0545] {logging_mixin.py:190} WARNING - /home/ashok/mlops_project/airflow/dags/mlops_diabetes_pipeline.py:439 UserWarning: Starting a Matplotlib GUI outside of the main thread will likely fail.
[2025-09-21T09:46:48.570+0545] {logging_mixin.py:190} WARNING - /home/ashok/mlops_project/airflow/dags/mlops_diabetes_pipeline.py:448 UserWarning: Starting a Matplotlib GUI outside of the main thread will likely fail.
[2025-09-21T09:46:48.574+0545] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/ashok/miniconda3/envs/mysecondenvironment/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/ashok/miniconda3/envs/mysecondenvironment/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/ashok/miniconda3/envs/mysecondenvironment/lib/python3.8/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/ashok/miniconda3/envs/mysecondenvironment/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
  File "/home/ashok/miniconda3/envs/mysecondenvironment/lib/python3.8/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/ashok/miniconda3/envs/mysecondenvironment/lib/python3.8/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/ashok/miniconda3/envs/mysecondenvironment/lib/python3.8/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/ashok/mlops_project/airflow/dags/mlops_diabetes_pipeline.py", line 449, in generate_shap_plots_from_redis
    shap.plots.bar(shap_values[i], show=False)
  File "/home/ashok/miniconda3/envs/mysecondenvironment/lib/python3.8/site-packages/shap/plots/_bar.py", line 66, in bar
    raise TypeError(emsg)
TypeError: The shap_values argument must be an Explanation object, Cohorts object, or dictionary of Explanation objects!
[2025-09-21T09:46:48.579+0545] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-09-21T09:46:48.579+0545] {logging_mixin.py:190} INFO - Task start:2025-09-21 04:01:46.290301+00:00 end:2025-09-21 04:01:48.579478+00:00 duration:2.289177
[2025-09-21T09:46:48.580+0545] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): generate_shap_explanations> dag:<DAG: mlops_diabetes_pipeline> dagrun:<DagRun mlops_diabetes_pipeline @ 2025-09-21 04:00:40.530929+00:00: manual__2025-09-21T04:00:40.530929+00:00, state:running, queued_at: 2025-09-21 04:00:40.537526+00:00. externally triggered: True>
[2025-09-21T09:46:48.580+0545] {logging_mixin.py:190} INFO - Failure caused by The shap_values argument must be an Explanation object, Cohorts object, or dictionary of Explanation objects!
[2025-09-21T09:46:48.580+0545] {taskinstance.py:1226} INFO - Marking task as UP_FOR_RETRY. dag_id=mlops_diabetes_pipeline, task_id=generate_shap_explanations, run_id=manual__2025-09-21T04:00:40.530929+00:00, execution_date=20250921T040040, start_date=20250921T040146, end_date=20250921T040148
[2025-09-21T09:46:48.586+0545] {base.py:84} INFO - Retrieving connection 'smtp_default'
[2025-09-21T09:46:48.587+0545] {email.py:272} INFO - Email alerting: attempt 1
[2025-09-21T09:46:53.707+0545] {email.py:283} INFO - Sent an alert email to ['koiralaashok02@gmail.com']
[2025-09-21T09:46:55.800+0545] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-09-21T09:46:55.800+0545] {standard_task_runner.py:124} ERROR - Failed to execute job 725 for task generate_shap_explanations (The shap_values argument must be an Explanation object, Cohorts object, or dictionary of Explanation objects!; 52011)
Traceback (most recent call last):
  File "/home/ashok/miniconda3/envs/mysecondenvironment/lib/python3.8/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/home/ashok/miniconda3/envs/mysecondenvironment/lib/python3.8/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/home/ashok/miniconda3/envs/mysecondenvironment/lib/python3.8/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
  File "/home/ashok/miniconda3/envs/mysecondenvironment/lib/python3.8/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/home/ashok/miniconda3/envs/mysecondenvironment/lib/python3.8/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/home/ashok/miniconda3/envs/mysecondenvironment/lib/python3.8/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/home/ashok/miniconda3/envs/mysecondenvironment/lib/python3.8/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/ashok/miniconda3/envs/mysecondenvironment/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
  File "/home/ashok/miniconda3/envs/mysecondenvironment/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/ashok/miniconda3/envs/mysecondenvironment/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/ashok/miniconda3/envs/mysecondenvironment/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/home/ashok/miniconda3/envs/mysecondenvironment/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/ashok/miniconda3/envs/mysecondenvironment/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/ashok/miniconda3/envs/mysecondenvironment/lib/python3.8/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/ashok/miniconda3/envs/mysecondenvironment/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
  File "/home/ashok/miniconda3/envs/mysecondenvironment/lib/python3.8/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/ashok/miniconda3/envs/mysecondenvironment/lib/python3.8/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/ashok/miniconda3/envs/mysecondenvironment/lib/python3.8/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/ashok/mlops_project/airflow/dags/mlops_diabetes_pipeline.py", line 449, in generate_shap_plots_from_redis
    shap.plots.bar(shap_values[i], show=False)
  File "/home/ashok/miniconda3/envs/mysecondenvironment/lib/python3.8/site-packages/shap/plots/_bar.py", line 66, in bar
    raise TypeError(emsg)
TypeError: The shap_values argument must be an Explanation object, Cohorts object, or dictionary of Explanation objects!
[2025-09-21T09:46:55.829+0545] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-09-21T09:46:55.836+0545] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-09-21T09:46:55.837+0545] {local_task_job_runner.py:245} INFO - ::endgroup::
